#!/usr/bin/env bash
# displays "To infinity and beyond"
# a sleep 2 between each iteration.
# displays "I am invincible!!!" in between each iteration.

while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invincible!!!"' SIGTERM
done
